### ISSUE TITLE
Errors on polling and getting poll result

### ISSUE THREAD

**Issue by hutoroff** [hutoroff/jagpb#10]
When users are polling registered errors:
```
MID: WARN  [PollService:vote:55] Option (id: 𦂗𢑪ꇿﻴ⎣윢) to vote for was not found in poll with _id: 5a93a2c4e5a95f02a5ea277d
MID: ERROR [PollingBot:onUpdateReceived:80] Error on update message with poll result: org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error editing message text
        at org.telegram.telegrambots.api.methods.updatingmessages.EditMessageText.deserializeResponse(EditMessageText.java:170)
        at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:672)
        at org.telegram.telegrambots.bots.AbsSender.execute(AbsSender.java:53)
        at ru.hutoroff.jagpb.bot.PollingBot.onUpdateReceived(PollingBot.java:78)
        at java.util.ArrayList.forEach(ArrayList.java:1255)
        at org.telegram.telegrambots.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27)
        at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:306)
```

On getting poll result:
```
MID: ERROR [PollingBot:sendReply:174] Error on sending reply:org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error sending message
        at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:170)
        at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:24)
        at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:672)
        at org.telegram.telegrambots.bots.AbsSender.execute(AbsSender.java:53)
        at ru.hutoroff.jagpb.bot.PollingBot.sendReply(PollingBot.java:172)
        at ru.hutoroff.jagpb.bot.PollingBot.doSimpleReply(PollingBot.java:167)
        at ru.hutoroff.jagpb.bot.PollingBot.executeCommand(PollingBot.java:129)
        at ru.hutoroff.jagpb.bot.PollingBot.processCommand(PollingBot.java:100)
        at ru.hutoroff.jagpb.bot.PollingBot.onUpdateReceived(PollingBot.java:56)
        at java.util.ArrayList.forEach(ArrayList.java:1255)
        at org.telegram.telegrambots.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27)
        at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:306)
```

**Comment by hutoroff** [comment]
It was error, that was not printed in stack trace:
`Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 115`
It was caused with incorrect usage of message markdown.
